name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: allTests
      id: alltests
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: allTests
        setup-command: ''
        command: gradle test
        timeout: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        ALLTESTS_RESULTS: "${{steps.alltests.outputs.result}}"
      with:
        runners: alltests
